# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_condominio', models.IntegerField(unique=True)),
                ('nome_condominio', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoContas', models.CharField(max_length=60)),
                ('codigo_conta', models.IntegerField(unique=True)),
                ('condominio', models.CharField(max_length=60)),
                ('cpf_inquilino', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome_inquilino', models.CharField(max_length=60)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vencimento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grupo', models.IntegerField(unique=True)),
                ('nome_grupo', models.CharField(max_length=50, unique=True, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_inquilino', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg_innuqilino', models.IntegerField()),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('nome_inquilino', models.CharField(max_length=30)),
                ('sobrenome_inquilino', models.CharField(max_length=30)),
                ('sexo_inquilino', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
    ]
